name: Review Tracker

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  fetch_reviews:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python review_tracker.py
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}